application: orgreminders
version: 4c
runtime: go
api_version: go1
instance_class: F1

handlers:
- url: /(.*\.(gif|png|jpg))$
  static_files: tmpl/\1
  upload: tmpl/.*\.(gif|png|jpg)$
  secure: always
- url: /
  script: _go_app
  secure: always
- url: /cron
  script: _go_app
  secure: always
  login: admin
- url: /.*
  script: _go_app  
  login: required
  secure: always
